---
# vim:ft=ansible:

- hosts: debops_service_telegraf
  become: True
  roles:
    - role: debops.influxdb
      influxdb__server: '{{ telegraf__influxdb_server }}'
      influxdb__users:
        - user: '{{ telegraf__influxdb_user }}'
      influxdb__databases:
        - database: '{{ telegraf__influxdb_database }}'
      influxdb__premissions:
        - user: '{{ telegraf__influxdb_user }}'
          database: '{{ telegraf__influxdb_database }}'
          premissions: 'ALL'
      tags: [ 'role::influxdb' ]

    - role: debops.telegraf
      tags: [ 'role::telegraf' ]
