---
# tasks file for debops.telegraf

#- debug:
#    var: telegraf__influxdb_password_path

#- fail:

- name: Ensure telegraf packages are installed
  apt:
    name: '{{ debops_telegraf__base_packages }}'
    state: latest

- name: Enable telegraf service
  service:
    name: telegraf
    enabled: yes
    state: started

- name: Configure Telegraf
  template:
    src: 'etc/telegraf/telegraf.conf.j2'
    dest: '/etc/telegraf/telegraf.conf'
  notify:
    - 'Restart telegraf'
