---
# vim:ft=ansible:

- name: Prepare InfluxDB account
  hosts: 'debops_service_telegraf'
  become: True

  roles:
    - role: debops.telegraf/env
      when: telegraf__outputs_influxdb_enabled
    - role: debops.influxdb
      influxdb__server: '{{ telegraf__outputs_influxdb_server }}'
      influxdb__users:
        - user: '{{ telegraf__outputs_influxdb_user }}'
      influxdb__databases:
        - database: '{{ telegraf__outputs_influxdb_database }}'
      influxdb__premissions:
        - user: '{{ telegraf__outputs_influxdb_user }}'
          database: '{{ telegraf__outputs_influxdb_database }}'
          premissions: 'ALL'
      tags: [ 'role::influxdb' ]
      when: telegraf__outputs_influxdb_enabled

- name: Manage Telegraf
  hosts: 'debops_service_telegraf'
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:
    - role: debops.secret
      tags: [ 'role::secret', 'role::telegraf' ]
    - role: debops.influxdata
      tags: [ 'role::influxdata' ]
      influxdata__dependent_packages:
        - '{{ telegraf__influxdata__dependent_packages }}'
    - role: debops.telegraf
      tags: [ 'role::telegraf' ]
      
